### ISSUE TITLE
Update htaccess for Apache 2.4

### ISSUE THREAD

**Issue by oskay** [locii/zgf4-htaccess#1]
Syntax is out of date; file causes 500 error on Apache 2.4

Solution available here:
http://stackoverflow.com/questions/22074614/htaccess-file-and-different-apache-versions

http://stackoverflow.com/questions/22475131/htaccess-filterprovider-giving-error-500

**Comment by robwent** [comment]
Fixed with https://github.com/locii/zgf4-htaccess/pull/3
